.TH "DerivedThree" 3 "Thu Mar 23 2017" "Version 1.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DerivedThree
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Classes\&.h>\fP
.PP
Inherits \fBDerivedTwo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDerivedThree\fP ()"
.br
.RI "A constructor\&. "
.ti -1c
.RI "virtual void \fBmethod_a\fP () const"
.br
.RI "A normal member taking two arguments and returning an integer value\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBDerivedThree\fP class Level 3 class\&. \fBBase\fP class description\&. 
.PP
Definition at line 168 of file Classes\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DerivedThree::DerivedThree ()\fC [inline]\fP"

.PP
A constructor\&. A more elaborate description of the constructor\&. 
.PP
Definition at line 175 of file Classes\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void DerivedThree::method_a () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
A normal member taking two arguments and returning an integer value\&. nparam a an integer argument\&. nparam s a constant character pointer\&. nreturn The test results nsa QTstyle_Test(), ~QTstyle_Test(), testMeToo() and publicVar() 
.PP
Reimplemented from \fBDerivedTwo\fP\&.
.PP
Definition at line 184 of file Classes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
