.TH "DerivedOne" 3 "Thu Mar 23 2017" "Version 1.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DerivedOne
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Classes\&.h>\fP
.PP
Inherits \fBBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDerivedOne\fP ()"
.br
.RI "A constructor\&. "
.ti -1c
.RI "virtual void \fBmethod_a\fP () const"
.br
.RI "A normal member taking two arguments and returning an integer value\&. "
.ti -1c
.RI "virtual void \fBset_external\fP (\fBExternal\fP *ex)"
.br
.RI "A normal member taking two arguments and returning an integer value\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExternal\fP * \fBpex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDerivedOne\fP class Level 2 class\&. \fBBase\fP class description\&. 
.PP
Definition at line 86 of file Classes\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DerivedOne::DerivedOne ()\fC [inline]\fP"

.PP
A constructor\&. A more elaborate description of the constructor\&. 
.PP
Definition at line 93 of file Classes\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void DerivedOne::method_a () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
A normal member taking two arguments and returning an integer value\&. nparam a an integer argument\&. nparam s a constant character pointer\&. nreturn The test results nsa QTstyle_Test(), ~QTstyle_Test(), testMeToo() and publicVar() 
.PP
Implements \fBBase\fP\&.
.PP
Definition at line 102 of file Classes\&.h\&.
.SS "virtual void DerivedOne::set_external (\fBExternal\fP * ex)\fC [inline]\fP, \fC [virtual]\fP"

.PP
A normal member taking two arguments and returning an integer value\&. nparam a an integer argument\&. nparam s a constant character pointer\&. nreturn The test results nsa QTstyle_Test(), ~QTstyle_Test(), testMeToo() and publicVar() 
.PP
Implements \fBBase\fP\&.
.PP
Definition at line 114 of file Classes\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBExternal\fP* DerivedOne::pex"

.PP
Definition at line 119 of file Classes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
