.TH "ExtImplement" 3 "Thu Mar 23 2017" "Version 1.0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExtImplement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Classes\&.h>\fP
.PP
Inherits \fBExternal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExtImplement\fP ()"
.br
.RI "A constructor\&. "
.ti -1c
.RI "virtual void \fBmethod_external\fP () const"
.br
.RI "A normal member taking two arguments and returning an integer value\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBExtImplement\fP class Some external class\&. \fBBase\fP class description\&. 
.PP
Definition at line 32 of file Classes\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExtImplement::ExtImplement ()\fC [inline]\fP"

.PP
A constructor\&. A more elaborate description of the constructor\&. 
.PP
Definition at line 39 of file Classes\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void ExtImplement::method_external () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
A normal member taking two arguments and returning an integer value\&. nparam a an integer argument\&. nparam s a constant character pointer\&. nreturn The test results nsa QTstyle_Test(), ~QTstyle_Test(), testMeToo() and publicVar() 
.PP
Implements \fBExternal\fP\&.
.PP
Definition at line 48 of file Classes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
